<?xml version="1.0" encoding="utf-8"?>

<wsdl:definitions name="NotificationConsumer"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"  
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2002/12/policy"
	xmlns:wsnc="http://www.nortel.com/soa/oi/cct/types/NotificationConsumer"
	xmlns:wsncw="http://www.nortel.com/soa/oi/cct/NotificationConsumer"
	xmlns:tns="http://www.nortel.com/soa/oi/cct/NotificationConsumer"
	targetNamespace="http://www.nortel.com/soa/oi/cct/NotificationConsumer">

	<wsdl:types>
		<xsd:schema 
			elementFormDefault="qualified" 
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.nortel.com/soa/oi/cct/NotificationConsumer">
			<xsd:import namespace="http://www.nortel.com/soa/oi/cct/types/NotificationConsumer" schemaLocation="NotificationConsumer.xsd"></xsd:import>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="Notify">
		<wsdl:part name="Notify" element="wsnc:Notify"/>
	</wsdl:message>

	<wsdl:portType name="NotificationConsumer">
		<wsdl:operation name="Notify">
			<wsdl:input message="wsncw:Notify" />
		</wsdl:operation>
	</wsdl:portType>
 
</wsdl:definitions>
