<?xml version="1.0" encoding="UTF-8"?>

<wsdl:definitions name="agent_terminal_connection_service_interface"
	targetNamespace="http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService"
	xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:service="http://www.nortel.com/soa/oi/cct/AgentTerminalConnectionService"
	xmlns:types="http://www.nortel.com/soa/oi/cct/types"
	xmlns:exceptions="http://www.nortel.com/soa/oi/cct/faults"
	xmlns:local="http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService">

	<wsdl:import 
		namespace="http://www.nortel.com/soa/oi/cct/faults"
		location="SessionServiceExceptions.wsdl" />

	<wsdl:types>

		<xsd:schema elementFormDefault="qualified"
			xmlns:xsd="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://www.nortel.com/soa/oi/cct/types/AgentTerminalConnectionService">

			<xsd:import
				namespace="http://www.nortel.com/soa/oi/cct/types"
				schemaLocation="types.xsd">
			</xsd:import>

			<xsd:complexType name="TerminalConnectionRequest">
				<xsd:sequence>
				<xsd:element name="ssoToken" type="types:ssoToken" />
					<xsd:element name="terminalConnection" type="types:terminalConnection" />					
				</xsd:sequence>
			</xsd:complexType>
			
			<xsd:complexType name="TerminalContactRequest">
				<xsd:sequence>
					<xsd:element name="ssoToken" type="types:ssoToken" />
					<xsd:element name="terminal" type="types:terminal" />
					<xsd:element name="contact" type="types:contact" />
				</xsd:sequence>
			</xsd:complexType>

			<xsd:complexType name="TerminalResponse">
				<xsd:sequence>
					<xsd:element name="terminal" type="types:terminal" />					
				</xsd:sequence>
			</xsd:complexType>
			
			<xsd:complexType name="ContactResponse">
				<xsd:sequence>
					<xsd:element name="contact" type="types:contact" />					
				</xsd:sequence>
			</xsd:complexType>
						
			<xsd:complexType name="GetAgentTerminalConnectionCapabilitiesResponse">
				<xsd:sequence>
					<xsd:element name="agentTerminalConnectionCapabilities" type="types:agentTerminalConnectionCapabilities" />					
				</xsd:sequence>
			</xsd:complexType>
								
			<xsd:complexType name="ConnectionResponse">
				<xsd:sequence>
					<xsd:element name="connection" type="types:connection" />					
				</xsd:sequence>
			</xsd:complexType>		
			
			<xsd:complexType name="StateResponse">
				<xsd:sequence>
					<xsd:element name="stateInfo" type="types:stateInfo" />					
				</xsd:sequence>
			</xsd:complexType>
			
			<xsd:complexType name="TerminalConnectionStateResponse">
				<xsd:sequence>
					<xsd:element name="terminalConnectionStateInfo" type="types:terminalConnectionStateInfo" />
				</xsd:sequence>
			</xsd:complexType>
			
			<xsd:complexType name="GetActivityCodeResponse">
				<xsd:sequence>
					<xsd:element name="activityCode" type="xsd:string"/>
				</xsd:sequence>
			</xsd:complexType>
			
			<xsd:complexType name="SetActivityCodeRequest">
				<xsd:sequence>
					<xsd:element name="ssoToken" type="types:ssoToken" />
					<xsd:element name="terminalConnection" type="types:terminalConnection" />
					<xsd:element name="activityCode" type="xsd:string" />					
				</xsd:sequence>
			</xsd:complexType>			
			
			<xsd:element name="GetVersionRequest" type="types:getVersionRequest" />					
			<xsd:element name="GetVersionResponse" type="types:getVersionResponse" />
								
			<xsd:element name="GetTerminalRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetTerminalResponse" type="local:TerminalResponse" />
			
			<xsd:element name="GetTerminalConnectionCapabilitiesRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetTerminalConnectionCapabilitiesResponse" type="local:GetAgentTerminalConnectionCapabilitiesResponse" />
			
			<xsd:element name="GetContactRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetContactResponse" type="local:ContactResponse" />
			
			<xsd:element name="GetConferenceConsultContactRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetConferenceConsultContactResponse" type="local:ContactResponse" />
			
			
			<xsd:element name="GetConnectionRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetConnectionResponse" type="local:ConnectionResponse" />
			
			<xsd:element name="GetStateRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetStateResponse" type="local:TerminalConnectionStateResponse" />
			
			<xsd:element name="GetTransferConsultContactRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetTransferConsultContactResponse" type="local:ContactResponse" />
			
			<xsd:element name="GetConsultContactRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetConsultContactResponse" type="local:ContactResponse" />
			
			<xsd:element name="EmergencyKeyRequest" type="local:TerminalContactRequest" />					
			<xsd:element name="EmergencyKeyResponse" type="local:ContactResponse" />
			
			<xsd:element name="GetActivityCodeRequest" type="local:TerminalConnectionRequest" />					
			<xsd:element name="GetActivityCodeResponse" type="local:GetActivityCodeResponse" />
			<xsd:element name="SetActivityCodeRequest" type="local:SetActivityCodeRequest" />
				
		</xsd:schema>
	</wsdl:types>
	
	<wsdl:message name="GetVersionRequest">	
		<wsdl:part name="parameters" element="local:GetVersionRequest" />
	</wsdl:message>
	<wsdl:message name="GetVersionResponse">
	<wsdl:part name="response" element="local:GetVersionResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetTerminalRequest">	
		<wsdl:part name="parameters" element="local:GetTerminalRequest" />
	</wsdl:message>
	<wsdl:message name="GetTerminalResponse">
	<wsdl:part name="response" element="local:GetTerminalResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetConferenceConsultContactRequest">	
		<wsdl:part name="parameters" element="local:GetConferenceConsultContactRequest" />
	</wsdl:message>
	<wsdl:message name="GetConferenceConsultContactResponse">
	<wsdl:part name="response" element="local:GetConferenceConsultContactResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetConsultContactRequest">	
		<wsdl:part name="parameters" element="local:GetConsultContactRequest" />
	</wsdl:message>
	<wsdl:message name="GetConsultContactResponse">
	<wsdl:part name="response" element="local:GetConsultContactResponse" />
	</wsdl:message>
	

	<wsdl:message name="GetTerminalConnectionCapabilitiesRequest">	
		<wsdl:part name="parameters" element="local:GetTerminalConnectionCapabilitiesRequest" />
	</wsdl:message>
	<wsdl:message name="GetTerminalConnectionCapabilitiesResponse">
	<wsdl:part name="response" element="local:GetTerminalConnectionCapabilitiesResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetContactRequest">	
		<wsdl:part name="parameters" element="local:GetContactRequest" />
	</wsdl:message>
	<wsdl:message name="GetContactResponse">
	<wsdl:part name="response" element="local:GetContactResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetStateRequest">	
		<wsdl:part name="parameters" element="local:GetStateRequest" />
	</wsdl:message>
	<wsdl:message name="GetStateResponse">
	<wsdl:part name="response" element="local:GetStateResponse" />
	</wsdl:message>
	
	<wsdl:message name="GetConnectionRequest">	
		<wsdl:part name="parameters" element="local:GetConnectionRequest" />
	</wsdl:message>
	<wsdl:message name="GetConnectionResponse">
	<wsdl:part name="response" element="local:GetConnectionResponse" />
	</wsdl:message>
	
	
	<wsdl:message name="GetTransferConsultContactRequest">	
		<wsdl:part name="parameters" element="local:GetTransferConsultContactRequest" />
	</wsdl:message>
	<wsdl:message name="GetTransferConsultContactResponse">
	<wsdl:part name="response" element="local:GetTransferConsultContactResponse" />
	</wsdl:message>
	
	<wsdl:message name="EmergencyKeyRequest">
		<wsdl:part name="parameters" element="local:EmergencyKeyRequest" />
	</wsdl:message>

	<wsdl:message name="EmergencyKeyResponse" />
	
	<wsdl:message name="SetActivityCodeRequest">
		<wsdl:part name="parameters" element="local:SetActivityCodeRequest" />
	</wsdl:message>

	<wsdl:message name="SetActivityCodeResponse"></wsdl:message>

	<wsdl:message name="GetActivityCodeRequest">
		<wsdl:part name="parameters" element="local:GetActivityCodeRequest" />
	</wsdl:message>
	
	<wsdl:message name="GetActivityCodeResponse">
		<wsdl:part name="response" element="local:GetActivityCodeResponse" />
	</wsdl:message>
	
	
	<wsdl:portType name="AgentTerminalConnectionService">

		<wsdl:operation name="GetVersion">
			<wsdl:input message="service:GetVersionRequest" />
			<wsdl:output message="service:GetVersionResponse" />
			<wsdl:fault name="SessionNotCreatedException" message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetVersionException" message="exceptions:GetVersionException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetConferenceConsultContact">
			<wsdl:input message="service:GetConferenceConsultContactRequest" />
			<wsdl:output message="service:GetConferenceConsultContactResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetConferenceConsultContactException"
				message="exceptions:GetConferenceConsultContactException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetConsultContact">
			<wsdl:input message="service:GetConsultContactRequest" />
			<wsdl:output message="service:GetConsultContactResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetConsultContactException"
				message="exceptions:GetConsultContactException" />
		</wsdl:operation>

		<wsdl:operation name="GetTerminalConnectionCapabilities">
			<wsdl:input message="service:GetTerminalConnectionCapabilitiesRequest" />
			<wsdl:output message="service:GetTerminalConnectionCapabilitiesResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetTerminalConnectionCapabilitiesException"
				message="exceptions:GetTerminalConnectionCapabilitiesException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetContact">
			<wsdl:input message="service:GetContactRequest" />
			<wsdl:output message="service:GetContactResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetContactException"
				message="exceptions:GetContactException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetState">
			<wsdl:input message="service:GetStateRequest" />
			<wsdl:output message="service:GetStateResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetStateException"
				message="exceptions:GetStateException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetConnection">
			<wsdl:input message="service:GetConnectionRequest" />
			<wsdl:output message="service:GetConnectionResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetConnectionException"
				message="exceptions:GetConnectionException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetTerminal">
			<wsdl:input message="service:GetTerminalRequest" />
			<wsdl:output message="service:GetTerminalResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetTerminalException"
				message="exceptions:GetTerminalException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetTransferConsultContact">
			<wsdl:input message="service:GetTransferConsultContactRequest" />
			<wsdl:output message="service:GetTransferConsultContactResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetTransferConsultContactException"
				message="exceptions:GetTransferConsultContactException" />
		</wsdl:operation>
		
		<wsdl:operation name="EmergencyKey">
			<wsdl:input name="EmergencyKeyRequest" message="service:EmergencyKeyRequest" />
			<wsdl:output name="EmergencyKeyResponse" message="service:EmergencyKeyResponse" />
			<wsdl:fault name="SessionNotCreatedException" message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="EmergencyKeyException" message="exceptions:EmergencyKeyException" />
		</wsdl:operation>
		
		<wsdl:operation name="GetActivityCode">
			<wsdl:input message="service:GetActivityCodeRequest" />
			<wsdl:output message="service:GetActivityCodeResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="GetActivityCodeException"
				message="exceptions:GetActivityCodeException" />
		</wsdl:operation>
		
		<wsdl:operation name="SetActivityCode">
			<wsdl:input message="service:SetActivityCodeRequest" />
			<wsdl:output message="service:SetActivityCodeResponse" />
			<wsdl:fault name="SessionNotCreatedException"
				message="exceptions:SessionNotCreatedException" />
			<wsdl:fault name="SetActivityCodeException"
				message="exceptions:SetActivityCodeException" />
		</wsdl:operation>
		
	</wsdl:portType>



</wsdl:definitions>
