<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://nortel.com/CCMMAgentWebservices/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:s1="http://datatypes.agentwebservices.ccmm.applications.nortel.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://nortel.com/CCMMAgentWebservices/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://nortel.com/CCMMAgentWebservices/">
      <s:import namespace="http://datatypes.agentwebservices.ccmm.applications.nortel.com" />
      <s:element name="ReadContact">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="id" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="sessionKey" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="ReadContactResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="ReadContactResult" type="s1:AWContact" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CloseContact">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="id" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="closureText" type="s:string" />
            <s:element minOccurs="1" maxOccurs="1" name="closedReasonCodeValue" type="s:long" />
            <s:element minOccurs="1" maxOccurs="1" name="closedReasonCodeSpecified" type="s:boolean" />
            <s:element minOccurs="0" maxOccurs="1" name="sessionKey" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="CloseContactResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="1" maxOccurs="1" name="CloseContactResult" type="s:long" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetAllClosedReasonCodes">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="sessionKey" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="GetAllClosedReasonCodesResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="GetAllClosedReasonCodesResult" type="tns:ArrayOfAWClosedReasonCode" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:complexType name="ArrayOfAWClosedReasonCode">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="AWClosedReasonCode" nillable="true" type="s1:AWClosedReasonCode" />
        </s:sequence>
      </s:complexType>
    </s:schema>
    <s:schema elementFormDefault="qualified" targetNamespace="http://datatypes.agentwebservices.ccmm.applications.nortel.com">
      <s:complexType name="AWContact">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="1" maxOccurs="1" name="customerID" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="originalSubject" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="source" type="s1:AWContactSource" />
          <s:element minOccurs="1" maxOccurs="1" name="status" type="s1:AWContactStatus" />
          <s:element minOccurs="0" maxOccurs="1" name="skillset" type="s1:AWSkillset" />
          <s:element minOccurs="1" maxOccurs="1" name="priority" type="s1:AWContactPriority" />
          <s:element minOccurs="1" maxOccurs="1" name="timezone" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="webOnHoldTag" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="arrivalTime" type="s1:AWDateTime" />
          <s:element minOccurs="0" maxOccurs="1" name="closedTime" type="s1:AWDateTime" />
          <s:element minOccurs="0" maxOccurs="1" name="openTime" type="s1:AWDateTime" />
          <s:element minOccurs="1" maxOccurs="1" name="openDuration" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="MailTo" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="MailFrom" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="MailCC" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="contactType" type="s1:AWContactType" />
          <s:element minOccurs="0" maxOccurs="1" name="agent" type="s1:AWAgent" />
          <s:element minOccurs="0" maxOccurs="1" name="actionList" type="s1:ArrayOfAWAction" />
          <s:element minOccurs="0" maxOccurs="1" name="customFieldList" type="s1:ArrayOfAWCustomField" />
        </s:sequence>
      </s:complexType>
      <s:simpleType name="AWContactSource">
        <s:restriction base="s:string">
          <s:enumeration value="NotAvailable" />
          <s:enumeration value="EMail" />
          <s:enumeration value="AgentCreated" />
          <s:enumeration value="Web" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:simpleType name="AWContactStatus">
        <s:restriction base="s:string">
          <s:enumeration value="New" />
          <s:enumeration value="Open" />
          <s:enumeration value="Closed" />
          <s:enumeration value="Waiting" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:complexType name="AWSkillset">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="name" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:simpleType name="AWContactPriority">
        <s:restriction base="s:string">
          <s:enumeration value="Priority_1_Highest" />
          <s:enumeration value="Priority_2_High" />
          <s:enumeration value="Priority_3_Medium_High" />
          <s:enumeration value="Priority_4_Medium_Low" />
          <s:enumeration value="Priority_5_Low" />
          <s:enumeration value="Priority_6_Lowest" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:complexType name="AWDateTime">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="milliseconds" type="s:long" />
        </s:sequence>
      </s:complexType>
      <s:simpleType name="AWContactType">
        <s:restriction base="s:string">
          <s:enumeration value="Fax" />
          <s:enumeration value="SMS" />
          <s:enumeration value="VoiceMail" />
          <s:enumeration value="WhiteMail" />
          <s:enumeration value="Other" />
          <s:enumeration value="ScheduledCallback" />
          <s:enumeration value="Voice" />
          <s:enumeration value="Email" />
          <s:enumeration value="Web_Communications" />
          <s:enumeration value="Outbound" />
          <s:enumeration value="Video" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:complexType name="AWAgent">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="firstName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="lastName" type="s:string" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfAWAction">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="AWAction" nillable="true" type="s1:AWAction" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="AWAction">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="1" maxOccurs="1" name="contactID" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="agent" type="s1:AWAgent" />
          <s:element minOccurs="0" maxOccurs="1" name="subject" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="text" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="textHTML" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="callbackTime" type="s1:AWDateTime" />
          <s:element minOccurs="1" maxOccurs="1" name="callbackStatus" type="s1:AWCallbackStatus" />
          <s:element minOccurs="0" maxOccurs="1" name="creationTime" type="s1:AWDateTime" />
          <s:element minOccurs="1" maxOccurs="1" name="source" type="s1:AWActionSource" />
          <s:element minOccurs="0" maxOccurs="1" name="mailFrom" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="mailTo" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="mailCC" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="mailBCC" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="comment" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="timeAllocated" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="numberUsed" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="outboundTalkTime" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="outboundDispositionCode" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="actionType" type="s1:AWContactType" />
          <s:element minOccurs="0" maxOccurs="1" name="customFieldList" type="s1:ArrayOfAWCustomField" />
          <s:element minOccurs="0" maxOccurs="1" name="closedReason" type="s1:AWClosedReasonCode" />
          <s:element minOccurs="0" maxOccurs="1" name="attachmentList" type="s1:ArrayOfAWAttachment" />
        </s:sequence>
      </s:complexType>
      <s:simpleType name="AWCallbackStatus">
        <s:restriction base="s:string">
          <s:enumeration value="Unknown" />
          <s:enumeration value="No_Callback" />
          <s:enumeration value="Call_Completed" />
          <s:enumeration value="Call_Not_Answered" />
          <s:enumeration value="Wrong_Telephone_Number" />
          <s:enumeration value="No_Number_Selected" />
          <s:enumeration value="Busy" />
          <s:enumeration value="Other" />
          <s:enumeration value="EMail_In_Queue" />
          <s:enumeration value="EMail_Sent" />
          <s:enumeration value="EMail_Undeliverable" />
          <s:enumeration value="EMail_Not_Sent" />
          <s:enumeration value="EMail_Address_Not_Provided" />
          <s:enumeration value="EMail_Received" />
          <s:enumeration value="EMail_Send_In_Progress" />
          <s:enumeration value="Fax_In_Queue" />
          <s:enumeration value="Fax_Sent" />
          <s:enumeration value="Wrong_Fax_Number" />
          <s:enumeration value="Fax_Not_Sent" />
          <s:enumeration value="Mail_Posted" />
          <s:enumeration value="Response_Cancelled" />
          <s:enumeration value="Web_reply" />
          <s:enumeration value="Contact_Closed" />
          <s:enumeration value="Contact_ReOpened" />
          <s:enumeration value="Contact_Transferred" />
          <s:enumeration value="Contact_Barred" />
          <s:enumeration value="Agent_Note" />
          <s:enumeration value="Chat_Response" />
          <s:enumeration value="Done" />
          <s:enumeration value="Created" />
          <s:enumeration value="Received" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:simpleType name="AWActionSource">
        <s:restriction base="s:string">
          <s:enumeration value="Not_Available" />
          <s:enumeration value="Automated_Response" />
          <s:enumeration value="EMail_from_Customer" />
          <s:enumeration value="EMail_from_Agent_to_Customer" />
          <s:enumeration value="Phone_from_Customer" />
          <s:enumeration value="Phone_from_Agent_to_Customer" />
          <s:enumeration value="Text_Chat_from_Customer" />
          <s:enumeration value="Text_Chat_from_Agent_to_Customer" />
          <s:enumeration value="Other_from_Customer" />
          <s:enumeration value="Other_from_Agent_to_Customer" />
          <s:enumeration value="Transfer_to_Agent" />
          <s:enumeration value="Transfer_to_Skillset" />
          <s:enumeration value="Transfer_to_External_Agent" />
          <s:enumeration value="Agent_Created_Contact" />
          <s:enumeration value="Agent_Created" />
          <s:enumeration value="Callback_Request_from_Customer" />
          <s:enumeration value="Password_Reminder_to_Customer" />
          <s:enumeration value="Outbound_Voice_Call_Not_Made" />
          <s:enumeration value="Supervisor_Closed" />
          <s:enumeration value="Customer_Abandoned_WebOnHold" />
          <s:enumeration value="Closed_By_Custom_Application" />
          <s:enumeration value="Unspecified" />
        </s:restriction>
      </s:simpleType>
      <s:complexType name="ArrayOfAWCustomField">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="AWCustomField" nillable="true" type="s1:AWCustomField" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="AWCustomField">
        <s:sequence>
          <s:element minOccurs="1" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="0" maxOccurs="1" name="name" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="text" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="isTextVisible" type="s:boolean" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="AWClosedReasonCode">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="name" type="s:string" />
          <s:element minOccurs="1" maxOccurs="1" name="numericValue" type="s:long" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="ArrayOfAWAttachment">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="unbounded" name="AWAttachment" nillable="true" type="s1:AWAttachment" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="AWAttachment">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="1" maxOccurs="1" name="idSpecified" type="s:boolean" />
          <s:element minOccurs="0" maxOccurs="1" name="displayFileName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="internalFileName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="direction" type="s1:AWCodeMapping" />
          <s:element minOccurs="0" maxOccurs="1" name="fileContents" type="s:base64Binary" />
        </s:sequence>
      </s:complexType>
      <s:complexType name="AWCodeMapping">
        <s:sequence>
          <s:element minOccurs="0" maxOccurs="1" name="id" type="s:long" />
          <s:element minOccurs="1" maxOccurs="1" name="idSpecified" type="s:boolean" />
          <s:element minOccurs="0" maxOccurs="1" name="fieldName" type="s:string" />
          <s:element minOccurs="0" maxOccurs="1" name="numericValue" type="s:long" />
          <s:element minOccurs="1" maxOccurs="1" name="numericValueSpecified" type="s:boolean" />
          <s:element minOccurs="0" maxOccurs="1" name="textValue" type="s:string" />
        </s:sequence>
      </s:complexType>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="ReadContactSoapIn">
    <wsdl:part name="parameters" element="tns:ReadContact" />
  </wsdl:message>
  <wsdl:message name="ReadContactSoapOut">
    <wsdl:part name="parameters" element="tns:ReadContactResponse" />
  </wsdl:message>
  <wsdl:message name="CloseContactSoapIn">
    <wsdl:part name="parameters" element="tns:CloseContact" />
  </wsdl:message>
  <wsdl:message name="CloseContactSoapOut">
    <wsdl:part name="parameters" element="tns:CloseContactResponse" />
  </wsdl:message>
  <wsdl:message name="GetAllClosedReasonCodesSoapIn">
    <wsdl:part name="parameters" element="tns:GetAllClosedReasonCodes" />
  </wsdl:message>
  <wsdl:message name="GetAllClosedReasonCodesSoapOut">
    <wsdl:part name="parameters" element="tns:GetAllClosedReasonCodesResponse" />
  </wsdl:message>
  <wsdl:portType name="AgentContactWSSoap">
    <wsdl:operation name="ReadContact">
      <wsdl:input message="tns:ReadContactSoapIn" />
      <wsdl:output message="tns:ReadContactSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="CloseContact">
      <wsdl:input message="tns:CloseContactSoapIn" />
      <wsdl:output message="tns:CloseContactSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="GetAllClosedReasonCodes">
      <wsdl:input message="tns:GetAllClosedReasonCodesSoapIn" />
      <wsdl:output message="tns:GetAllClosedReasonCodesSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AgentContactWSSoap" type="tns:AgentContactWSSoap">
    <wsdl:documentation>
      <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.1" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" />
    </wsdl:documentation>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ReadContact">
      <soap:operation soapAction="http://nortel.com/CCMMAgentWebservices/ReadContact" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CloseContact">
      <soap:operation soapAction="http://nortel.com/CCMMAgentWebservices/CloseContact" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllClosedReasonCodes">
      <soap:operation soapAction="http://nortel.com/CCMMAgentWebservices/GetAllClosedReasonCodes" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="AgentContactWSSoap12" type="tns:AgentContactWSSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="ReadContact">
      <soap12:operation soapAction="http://nortel.com/CCMMAgentWebservices/ReadContact" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="CloseContact">
      <soap12:operation soapAction="http://nortel.com/CCMMAgentWebservices/CloseContact" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="GetAllClosedReasonCodes">
      <soap12:operation soapAction="http://nortel.com/CCMMAgentWebservices/GetAllClosedReasonCodes" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AgentContactWS">
    <wsdl:port name="AgentContactWSSoap" binding="tns:AgentContactWSSoap">
      <soap:address location="https://ccmm-minchin/ccmmagentwebservices/AgentContactWS.asmx" />
    </wsdl:port>
    <wsdl:port name="AgentContactWSSoap12" binding="tns:AgentContactWSSoap12">
      <soap12:address location="https://ccmm-minchin/ccmmagentwebservices/AgentContactWS.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>