<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://nortel.com/CCMMAgentWebservices/" xmlns:s="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" targetNamespace="http://nortel.com/CCMMAgentWebservices/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <wsdl:types>
    <s:schema elementFormDefault="qualified" targetNamespace="http://nortel.com/CCMMAgentWebservices/">
      <s:element name="AgentDesktopLogin">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
            <s:element minOccurs="0" maxOccurs="1" name="password" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AgentDesktopLoginResponse">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="AgentDesktopLoginResult" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AgentDesktopLogoff">
        <s:complexType>
          <s:sequence>
            <s:element minOccurs="0" maxOccurs="1" name="username" type="s:string" />
          </s:sequence>
        </s:complexType>
      </s:element>
      <s:element name="AgentDesktopLogoffResponse">
        <s:complexType />
      </s:element>
    </s:schema>
  </wsdl:types>
  <wsdl:message name="AgentDesktopLoginSoapIn">
    <wsdl:part name="parameters" element="tns:AgentDesktopLogin" />
  </wsdl:message>
  <wsdl:message name="AgentDesktopLoginSoapOut">
    <wsdl:part name="parameters" element="tns:AgentDesktopLoginResponse" />
  </wsdl:message>
  <wsdl:message name="AgentDesktopLogoffSoapIn">
    <wsdl:part name="parameters" element="tns:AgentDesktopLogoff" />
  </wsdl:message>
  <wsdl:message name="AgentDesktopLogoffSoapOut">
    <wsdl:part name="parameters" element="tns:AgentDesktopLogoffResponse" />
  </wsdl:message>
  <wsdl:portType name="AgentUtilityWSSoap">
    <wsdl:operation name="AgentDesktopLogin">
      <wsdl:input message="tns:AgentDesktopLoginSoapIn" />
      <wsdl:output message="tns:AgentDesktopLoginSoapOut" />
    </wsdl:operation>
    <wsdl:operation name="AgentDesktopLogoff">
      <wsdl:input message="tns:AgentDesktopLogoffSoapIn" />
      <wsdl:output message="tns:AgentDesktopLogoffSoapOut" />
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AgentUtilityWSSoap" type="tns:AgentUtilityWSSoap">
    <wsdl:documentation>
      <wsi:Claim conformsTo="http://ws-i.org/profiles/basic/1.1" xmlns:wsi="http://ws-i.org/schemas/conformanceClaim/" />
    </wsdl:documentation>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="AgentDesktopLogin">
      <soap:operation soapAction="http://nortel.com/CCMMAgentWebservices/AgentDesktopLogin" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AgentDesktopLogoff">
      <soap:operation soapAction="http://nortel.com/CCMMAgentWebservices/AgentDesktopLogoff" style="document" />
      <wsdl:input>
        <soap:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:binding name="AgentUtilityWSSoap12" type="tns:AgentUtilityWSSoap">
    <soap12:binding transport="http://schemas.xmlsoap.org/soap/http" />
    <wsdl:operation name="AgentDesktopLogin">
      <soap12:operation soapAction="http://nortel.com/CCMMAgentWebservices/AgentDesktopLogin" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="AgentDesktopLogoff">
      <soap12:operation soapAction="http://nortel.com/CCMMAgentWebservices/AgentDesktopLogoff" style="document" />
      <wsdl:input>
        <soap12:body use="literal" />
      </wsdl:input>
      <wsdl:output>
        <soap12:body use="literal" />
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="AgentUtilityWS">
    <wsdl:port name="AgentUtilityWSSoap" binding="tns:AgentUtilityWSSoap">
      <soap:address location="https://ccmm-minchin/ccmmagentwebservices/AgentUtilityWS.asmx" />
    </wsdl:port>
    <wsdl:port name="AgentUtilityWSSoap12" binding="tns:AgentUtilityWSSoap12">
      <soap12:address location="https://ccmm-minchin/ccmmagentwebservices/AgentUtilityWS.asmx" />
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>